server:
  port: 9090
spring:
  application:
    name: admin-server

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

