debug: true
server:
  # start services on random port by default
  port: 0
  # The stop processing uses a timeout which provides a grace period during which existing requests will be allowed to complete but no new requests will be permitted
  shutdown: graceful

# embedded database init, supports mysql too trough the 'mysql' spring profile
spring:
  datasource:
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      # Allow the microservices to override the remote properties with their own System properties or config file
      allow-override: true
      # Override configuration with any local property source
      override-none: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  boot:
    admin:
      client:
        url: http://admin-server:9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# Temporary hack required by the Spring Boot 2 / Spring Cloud Finchley branch
# Waiting issue https://github.com/spring-projects/spring-boot/issues/13042
spring.cloud.refresh.refreshable: false


# Logging
logging.level.org.springframework: INFO

# Metrics
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      # indica que health deve mostrar detalhes sempre
      show-details: always
  endpoints:
    web:
      exposure:
        # alem do health e do info ele sempre vai export todos endpoints disponiveis
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false


---
spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://mysql_db:3306/petclinic?useSSL=false
    username: root
    password: petclinic
    initialization-mode: always
    platform: mysql