debug: true
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: mysql
    initialization-mode: always
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: admin@email.com
    password: email-password
    port: 587
    protocol: smtp
    debug: true
    smtp:
      auth: true
      starttls:
        enable: true

prop:
  swagger:
    enabled: false

security:
  jwt:
    secret: secret-key
    expiration: 300000 # /60/1000
    password-reset-duration: 3600000
    refresh-duration: 2592000000
    email-verification-duration: 3600000

cache:
  logoutToken:
    maxSize: 1000

velocity:
  templates:
    location: /templates/
