debug: true
server:
  port: 8081

spring:
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: admin@email.com
    password: email-password
    port: 587
    protocol: smtp
    debug: true
    smtp:
      auth: true
      starttls:
        enable: true

security:
  jwt:
    header: Authorization
    prefix: Bearer
    secret: secret-key
    expiration: 300000 # /60/1000
    password-reset-duration: 3600000
    refresh-duration: 2592000000
    email-verification-duration: 3600000
cache:
  logoutToken:
    maxSize: 1000
velocity:
  templates:
    location: /templates/
prop:
  swagger:
    enabled: true
  actuator:
    enabled: true