debug: false
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:9091/eureka}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password: root
    platform: mysql
    initialization-mode: always
    testWhileIdle: true
    validationQuery: SELECT 1

tomcat:
  max-wait: 20000
  max-active: 50
  max-idle: 20
  min-idle: 15

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      id:
        new_generator_mappings: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: admin@email.com
    password: email-password
    port: 587
    protocol: smtp
    debug: true
    smtp:
      auth: true
      starttls:
        enable: true

prop:
  swagger:
    enabled: false

security:
  jwt:
    secret: secret-key
    expiration: 300000 # /60/1000
    password-reset-duration: 3600000
    refresh-duration: 2592000000
    email-verification-duration: 3600000

cache:
  logoutToken:
    maxSize: 1000

velocity:
  templates:
    location: /templates/
