debug: true

spring:
  config:
    activate:
      on-profile: docker
  boot:
    admin:
      client:
        url: http://admin-server:9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:9091/eureka

