server:
  port: 8888

spring:
  boot:
    admin:
      client:
        url: http://admin-server:9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        # alem do health e do info ele sempre vai export todos endpoints disponiveis
        include: '*'
  endpoint:
    health:
      # indica que health deve mostrar detalhes sempre
      show-details: always