vets:
  cache:
    ttl: 60
    heap-size: 100

server:
  port: 8083

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
#this is a bug that needs to be resolved
management:
  metrics:
    export:
      wavefront:
        apiToken: ""

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
